version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pitest:
        patterns:
          - "org.pitest:*"
      spring:
        patterns:
          - "org.springframework:*"
          - "org.springframework.boot:*"
      atlassian-oai:
        patterns:
          - "com.atlassian.oai:*"