apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:community
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: devops-tools
spec:
  selector:
    app: sonarqube
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30900