name: PITest

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  run-pitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Run PITest
        run: |
          ./mvnw pitest:mutationCoverage

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: PITest Mutation Test Report
          path: target/pit-reports/